### ISSUE TITLE
Dragonflight update?

### ISSUE THREAD

**Issue by KnightDemons** [Haselnussbomber/MountInfo#1]
Any chance of an update and maybe mouse over for looking at other players mount buff?

**Comment by Haselnussbomber** [comment]
Hey there,

I'm not the original author and this was just my own little update to an addon I used a long time ago.
Therefore I can't update it on curseforge/wowinterface and I also won't publish it as "fan update", because I purely just update it so it still works for me. 🤷

For Dragonflight, I just adjusted the interface version number, so it doesn't show as out-of-date, and swapped the colors (now green for collected, red for not collected), because it makes more sense.

If you wish to use my version here, you can do that by simply downloading the repositories [archive](https://github.com/Haselnussbomber/MountInfo/archive/refs/heads/main.zip) and removing `-main` from the folders name.

Lastly, I'm sorry, but I won't add it to the unit tooltips. As I said, I just want this addon to keep working for myself and I don't like to have it in the unit tooltips. Maybe the author of MountTooltip will add collected status, as you already asked for. 🙂

**Comment by KnightDemons** [comment]
Was just looking for a fix because in it's current stance the mouseover mount buff only works on yourself, so kind of pointless for collected or not collected if you are indeed looking at your mount buff. 

Kind of confused why looking at another player's mount buff doesn't show any info like collected or not collected. 
![Wow_dl4HH2dXcP](https://user-images.githubusercontent.com/16524811/202051470-030b5557-3742-4177-b8d0-bbbfc4f858d2.png)
![InkedWow_VxCQgyVpmx](https://user-images.githubusercontent.com/16524811/202051495-7c0f22ce-2635-4ef5-8e31-b02045d6ba02.jpg)

**Comment by Haselnussbomber** [comment]
Ah, you're right! I was assuming it's the same for all spell tooltips and only checked my own buffs.^^
I figured it out though: it a new API using AuraInstanceIDs. Check out the updated [core.lua](https://github.com/Haselnussbomber/MountInfo/blob/main/core.lua). 😉
